import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaMariaDb } from "@prisma/adapter-mariadb";
const url = new URL(process.env.DATABASE_URL);
const a = new PrismaMariaDb({ host: url.hostname, port: parseInt(url.port||"3306"), user: url.username, password: url.password, database: url.pathname.replace("/",""), ssl:{rejectUnauthorized:false}});
const p=new PrismaClient({adapter:a});
await p.$executeRawUnsafe("ANALYZE TABLE pagos");
await p.$executeRawUnsafe("ANALYZE TABLE prestamos");
await p.$executeRawUnsafe("ANALYZE TABLE usuarios");
console.log("analyzed");
await p.$disconnect();
